task:
  environment:
    TELEGRAM_TOKEN: ENCRYPTED[!94fbd2d08de5b1a873f120ff1dde676de27ae81893c86a8393ad389227123de22ddf77b3e9c345f32892ba347fb82477!]
    TELEGRAM_CHAT: ENCRYPTED[!cb55d5185ebb9d6b6dff8d585e44d9bd8f31f0eb996167a4ccebad7a19749b474c31de5ac877c7a4941601b6388827ae!]
    BRANCH: tiramisu/mglru
    
  name: Build Kernel
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Build_script:
      - echo "LC_ALL=en_US.UTF-8" | sudo tee -a /etc/environment
      - echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
      - echo "LANG=en_US.UTF-8" | sudo tee -a /etc/locale.conf
      - sudo locale-gen en_US.UTF-8
      - wget https://raw.githubusercontent.com/XSans0/my-script/main/build.sh
      - bash build.sh
